---
title: 'Supplementary Analyses for: "Registered Multisite Replication of Tempting-Fate Effects in Risen & Gilovich (2008)" '

header-includes:
- \usepackage[T1]{fontenc}
- \usepackage{microtype}
- \usepackage[margin=1in]{geometry}
- \usepackage{fancyhdr}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[C]{Supplement}
- \fancyfoot[RO,LE]{\thepage}
- \usepackage{booktabs}
- \usepackage{lettrine}
- \usepackage{paralist}
- \usepackage{setspace}\singlespacing
- \usepackage[square,numbers,super]{natbib}
- \setcitestyle{square,numbers,super}
- \usepackage{url}
- \usepackage{parskip}
- \usepackage{color,soul}
- \usepackage{palatino}

output: pdf_document
citation_package: natbib
bibliography: refs_ml5.bib
---

```{r echo=FALSE, message=FALSE, results='hide', warning=FALSE}
# load all packages
library(tidyverse)
library(papaja)
library(knitr)
library(lme4)
library(stargazer)
library(metafor)
library(rmeta)
library(lmerTest)
library(Replicate)

rm( list = ls() )

# Option 1: re-run analyses and re-create plots
# source("helper.R")
# source("analysis.R")

# Option 2: use saved output from previous analysis run
load( "analysis_objects.rds" )

opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

\tableofcontents
\newpage


# Descriptive Statistics and Plots

## Cohen's $d$ and $t$-tests within each site

Per the preregistration, here we will conduct additional within-site analyses that reproduce the original study's stratified analyses and effect sizes of tempting fate. 



## Interaction plots by site type

We will show boxplots with medians and IQRs by experimental condition and site type. These aggregated means and SDs will pool across all sites within a group (similar, dissimilar, MTurk) and do not account for clustering by site.



## Cell means and standard deviations by site type

We show a table with means and SDs of perceived likelihood across all subjects within each site type (naively pooling all sites).


# Statistical Consistency of Original Study with Replications

We will conduct post hoc secondary analyses to assess the extent to which the replication findings were statistically consistent with the original study; that is, whether it is plausible that the original study was drawn from the same distribution as the replications (Mathur \& VanderWeele 2017). These analyses account for uncertainty in both the original study and the replication and for possible heterogeneity in the replications, and they can help distinguish whether an estimated effect size in the replications that appears to disagree with the original estimate may nevertheless be statistically consistent with the original study due, for example, to low power in the original study or in the replications or to heterogeneity.


# Sensitivity Analyses for Reported Results

## Fit subset model counterpart to primary analysis model

Instead of fitting a model that includes both MTurk and similar sites with an interaction of site type, we fit a model to only the subset of similar sites. We will report whether the point estimates and CIs are similar to those in the primary model. 



## Fit meta-analytic counterparts to primary analysis model


Instead of fitting a mixed model to observation-level data, we will fit random-effects meta-analyses to the point estimates using the Paule \& Mandel heterogeneity estimator and the Knapp-Hartung standard error adjustment. We will report whether the estimated main effect and heterogeneity are similar to those in the primary analyses. We will report whether $P_{orig}$ changes meaningfully with the meta-analytic estimates. 


## Combine all universities into one category

In the planned secondary analysis model including all universities, similar and dissimilar sites were treated as separate categories. Here, they will be combined into one category. 


## Refit original study's ANOVA model

The original study used two-way ANOVA to test for the main effect and interaction. Per our preregistered protocol, we also reproduce this model as a secondary analysis here. Since this model is statistically equivalent to the regression models presented in the main text, this is simply a different way of presenting the contrasts. 

